### ISSUE TITLE
Add info for yb_shoots_thru_walls 3

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/docs#3]
Write what happens when the value of this cvar is set to 3

**Comment by Vladislav4KZ** [comment]
@jeefo I found that there is also a value of 3 for the cvar yb_shoots_thru_walls. Can you explain or write about it in the documentation what it means.

**Comment by jeefo** [comment]
Nothing will happen. Valid value afaik 0,1,2

**Comment by Vladislav4KZ** [comment]
Got it, thanks
