### ISSUE TITLE
yapb auto graph download

### ISSUE THREAD

**Issue by DeclineD-Com-AMXX** [yapb/docs#6]
Can't download 'zm_vendetta.graph' from 'http://graph.yapb.ru/graph/zm_vendetta.graph' to 'cstrike/addons/yapb/data/graph/zm_vendetta.graph'... (-2).

Why does it say that?

**Comment by jeefo** [comment]
Error code -2 means - Socket connect error.

Just tested on current release, download works ok on my side.

**Comment by Vladislav4KZ** [comment]
Wrong repository
