### ISSUE TITLE
Ясное объяснение кваров yb_path_danger_factor

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/docs#9]
@jeefo В описании вышеуказанных кваров, полученных с помощью команды ``yb cvars`` пишется это:
yb_path_danger_factor_min
Lower bound of danger factor that used to add additional danger to path based on practice.

yb_path_danger_factor_max
Upper bound of danger factor that used to add additional danger to path based on practice.

Что значит фактор опасности который добавляет дополнительную опасность к пути основанной на практике? Что даст изменение этих кваров? Или в чём измеряются значения этих кваров?

В документации, я ещё давно вставил то же описание, которое выдаёт бот в консоли игры, но не особо понимаю что оно делает чтобы ясно объяснить в документации для чего его можно применять.

Мой второй коммент ниже, с другими вопросами почему-то продублировался, удалил один - исчез и второй. Приложение GitHub для Android глючит.

**Comment by Vladislav4KZ** [comment]
Я знаю, что во время игры собирается информация об опасных точках для каждой команды, на которых боты получали урон, которая сохраняется в файле данных практики.

Эти квары как-то влияют на эту инфу об опасности, но что будет если изменить значение? Если повысить значение, боты будут ещё более осторожными?

И так как там есть минимальное и максимальное значение порога фактора опасности, то значит выбирается какое-то случайное значение между ними, но в каких случаях? Или эти случайные значения у каждого бота свои?

Если что, извиняюсь за такое количество вопросов.

В документации, в отличие от описаний кваров в игре ведь можно писать подробнее. Я видел когда-то человека, который задавал такой же вопрос.

**Comment by jeefo** [comment]
опасные места будут ещё более опасными, в поиске путей точка будет применяться реже, однако если goal лежит через эту точку или нужен самый короткий путь, то эти квары мало на что повлияют

то есть на оба вопроса, всё верно, заставляет их быть более аккуратными, и значение выбирается случайно между двумя кварами

**Comment by Vladislav4KZ** [comment]
Спасибо за пояснение
